# Functions II

## EOSC 211

**Week 8 Day 2**

**Learning Objectives:**  
1. Implement functions in your code
2. Understand the difference between a *fruitful* function (one that returns a variable) and void functions (one that performs an action but does not return anything

## Question 1

**We have two input arrays, `x` which is distance and `tpro` which is elevation in kilometers (say, along a survey line). Both have shape (99,). Use a *loop* and an *if statement* to write out a new variable `tlow` that contains only the values in `tpro` when the elevation is less than -1.8km.**

In [11]:
import numpy as np

x = np.linspace(0, 1000, 100)  # km along the survey line
tpro = 2 * np.sin(x)  # get some real topographical data here instead?

# your code here

In [9]:
# andrew's soln
tlow = np.array([])
for i in tpro:
    if i < 0.5:
        tlow = np.append(tlow,i)

print(tlow)

[ 0.         -0.62585878 -0.89698277  0.42291893  0.23728303 -0.79305028
 -0.7664708   0.19582243  0.46101272 -0.91494363 -0.59217888 -0.04245923
 -0.98457643 -0.38406237 -0.27831567 -0.99797133 -0.15400864 -0.49827503
 -0.95436322  0.08484189 -0.68977348 -0.85624296  0.3445131   0.31884634
 -0.84187284 -0.70921506  0.11191708 -0.94588537 -0.52167759 -0.12707152
 -0.99586998 -0.30434248 -0.35880194 -0.98897162 -0.06962366 -0.570038
 -0.92558431  0.48498335  0.16907197 -0.74871412 -0.80932866  0.26362294
  0.39811041 -0.88462453 -0.64684506  0.02720468 -0.97000618 -0.4474144
 -0.21076748 -0.99998217 -0.22242793 -0.43670084 -0.97284029  0.01526338
 -0.63769034 -0.89013087  0.40903849  0.25208285 -0.80225568 -0.75657817
  0.18083175  0.47450364 -0.92099707 -0.57981057 -0.0577039  -0.98713214
 -0.36992484 -0.29294357]


## Question 2

**Turn the code snippet above into a function that returns an array `tlow` that is exactly the same as Q1, but that takes as input (1) `tproin` and (2) a variable called `cutoff` that contains an arbitrary cut-off for the elevation  (ie, I might want to select elevations below -2km or -1.8 km or -1.5km, so make this a variable).**

**Finally, call your function with tpro as the input data and a cutoff of 1.8km**

In [10]:
# your code here

In [13]:
# andrew's soln
def select_elev(in_data, cutoff):
    """
    selects elements of a 1D np array in_data which are below the value cutoff.
    returns elements of in_data which are below cutoff
    """
    tlow = np.array([])
    for i in tpro:
        if i < cutoff:
            tlow = np.append(tlow, i)
    return tlow

select_elev(tpro, -1.8)

array([-1.82988727, -1.96915287, -1.99594266, -1.90872645, -1.89177074,
       -1.99173997, -1.97794324, -1.85116862, -1.94001237, -1.99996433,
       -1.94568058, -1.84199414, -1.97426428])

## Question 3

**Modify your function to return a *tuple* containing the elevations below `cutoff`, and the *indexes* of where those elements are found; ie `(tlow, tlow_ind)`.**

In [14]:
# your code here

In [19]:
# andrew's soln
def select_elev2(in_data, cutoff):
    """
    selects elements of a 1D np array in_data which are below the value cutoff.
    returns elements of in_data which are below cutoff
    """
    tlow = np.array([])
    tlow_ind = np.array([])
    for i in range(len(in_data)):
        if in_data[i] < cutoff: 
            tlow_ind = np.append(tlow_ind, i)
            tlow = np.append(tlow, in_data[i])
    return tlow, tlow_ind

low, ind = select_elev2(tpro, -1.5)
low, ind

(array([-1.79396554, -1.58610056, -1.5329416 , -1.82988727, -1.96915287,
        -1.99594266, -1.90872645, -1.71248592, -1.68374568, -1.89177074,
        -1.99173997, -1.97794324, -1.85116862, -1.61865731, -1.76924907,
        -1.94001237, -1.99996433, -1.94568058, -1.78026173, -1.60451135,
        -1.51315633, -1.84199414, -1.97426428]),
 array([ 3.,  6.,  8., 11., 16., 21., 26., 31., 34., 39., 44., 49., 54.,
        59., 62., 67., 72., 77., 82., 85., 87., 90., 95.]))

## Question 4

**Finally, I need not have used a loop and an “if” statement in the function.  How would I rewrite the body of the function in Exercise 2 to use logical indexing?  Note that the function call and function definition line don’t need to be changed.**

In [20]:
# your code here

In [22]:
# andrew's soln
def select_elev3(in_data, cutoff):
    """
    selects elements of a 1D np array in_data which are below the value cutoff.
    returns elements of in_data which are below cutoff
    """
    return in_data[in_data < cutoff]
    
select_elev3(tpro, -1.8)

array([-1.82988727, -1.96915287, -1.99594266, -1.90872645, -1.89177074,
       -1.99173997, -1.97794324, -1.85116862, -1.94001237, -1.99996433,
       -1.94568058, -1.84199414, -1.97426428])